/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ia;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */
public class createacc extends javax.swing.JFrame {
Connection cin;
    ResultSet rs;
    PreparedStatement ps;
    
    /**
     * Creates new form createacc
     */
    public createacc() {
        initComponents();
          bg.setIcon(sql_connection.scaleimg(bg.getWidth(),bg.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logtext = new javax.swing.JLabel();
        mailtext = new javax.swing.JLabel();
        pwdtext = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        createacc = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        mailtext1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        mailtext2 = new javax.swing.JLabel();
        mailtext3 = new javax.swing.JLabel();
        conpwd = new javax.swing.JPasswordField();
        crtpwd = new javax.swing.JPasswordField();
        firstname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        showpwd = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logtext.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        logtext.setText("Create Account");
        jPanel2.add(logtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 310, 40));

        mailtext.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext.setText("Last Name");
        jPanel2.add(mailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        pwdtext.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        pwdtext.setText("Username");
        jPanel2.add(pwdtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        next.setBackground(new java.awt.Color(0, 163, 0));
        next.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 240, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setText("Already have an account?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        createacc.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        createacc.setText("Log In");
        createacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createaccMouseClicked(evt);
            }
        });
        jPanel2.add(createacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 80, -1));

        lastname.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lastname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastnameKeyTyped(evt);
            }
        });
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 220, -1));

        mailtext1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext1.setText("Confirm Password");
        jPanel2.add(mailtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        username.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 560, -1));

        mailtext2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext2.setText("First Name");
        jPanel2.add(mailtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        mailtext3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext3.setText("Create Password");
        jPanel2.add(mailtext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        conpwd.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        conpwd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(conpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 220, 30));

        crtpwd.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        crtpwd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(crtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 220, 30));

        firstname.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        firstname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnameKeyTyped(evt);
            }
        });
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 220, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 560, 10));

        showpwd.setBackground(new java.awt.Color(255, 255, 255));
        showpwd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        showpwd.setText("Show Password");
        showpwd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showpwdItemStateChanged(evt);
            }
        });
        jPanel2.add(showpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 640, 450));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
       //CHeck if all fields are filled 
        if(username.getText().equalsIgnoreCase("")||firstname.getText().equalsIgnoreCase("")||
           lastname.getText().equalsIgnoreCase("")||crtpwd.getText().equalsIgnoreCase("")||
           conpwd.getText().equalsIgnoreCase(""))
           JOptionPane.showMessageDialog(this," Please Fill All Fields");        
       else{
            if(crtpwd.getText().equals(conpwd.getText())){//Checking if both password fields are same
            createacc2 cra2=new createacc2( firstname.getText(),lastname.getText(),username.getText(), 
                                            crtpwd.getText());//Importing all values enterred here to the second form
            cra2.setVisible(true);        
            this.dispose();
            }
            else
            JOptionPane.showMessageDialog(null,"Passwords do not match!");
        }
    }//GEN-LAST:event_nextActionPerformed

    private void createaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccMouseClicked
        // TODO add your handling code here:
        //Go back to login screen
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createaccMouseClicked

    private void lastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameKeyTyped
        // TODO add your handling code here:
      

    }//GEN-LAST:event_lastnameKeyTyped

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
        // TODO add your handling code here:
        //Checking if username already exists
        try{
           
            //Connection establishment
            cin=sql_connection.conneect_DB();
            ps=cin.prepareStatement("SELECT * FROM users WHERE username=?");
             ps.setString(1, username.getText());
            rs=ps.executeQuery();
            if(rs.next()==true)
            {
                JOptionPane.showMessageDialog(this,"username already exists");

            }
            else
            {
            }
        }
        catch(SQLException ex){

        }
    }//GEN-LAST:event_usernameKeyReleased

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void firstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_firstnameKeyReleased

    private void firstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyTyped
        // TODO add your handling code here:

        
    }//GEN-LAST:event_firstnameKeyTyped

    private void showpwdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showpwdItemStateChanged
        // TODO add your handling code here:
        //SHow password 
        if(showpwd.isSelected()==true)
        {
            crtpwd.setEchoChar((char) 0);
            conpwd.setEchoChar((char) 0);
        }
        else
        {
            crtpwd.setEchoChar('*');
            conpwd.setEchoChar('*');
        }
    }//GEN-LAST:event_showpwdItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createacc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPasswordField conpwd;
    private javax.swing.JLabel createacc;
    private javax.swing.JPasswordField crtpwd;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel logtext;
    private javax.swing.JLabel mailtext;
    private javax.swing.JLabel mailtext1;
    private javax.swing.JLabel mailtext2;
    private javax.swing.JLabel mailtext3;
    private javax.swing.JButton next;
    private javax.swing.JLabel pwdtext;
    private javax.swing.JCheckBox showpwd;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
