/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ia;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */
public class createacc2 extends javax.swing.JFrame {

    ResultSet rs;
    PreparedStatement ps;
     String username="",firstname="",lastname="",pwd1="";
     public String st="";
 StringBuilder sb = new StringBuilder(6);
 
 
    public void captcha(){ //Autogenerating captacha code 
    String AlphaNumericString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                 + "0123456789"
                                 + "abcdefghijklmnopqrstuvxyz";
        // create StringBuffer size of AlphaNumericString
        for (int i = 0; i < 6; i++) {
            // generate a random number between
            // 0 to AlphaNumericString variable length
            int index = (int)(AlphaNumericString.length()
                        * Math.random());
              // add Character one by one in end of sb
            sb.append(AlphaNumericString.charAt(index));
            captcha.setText(sb.toString());
           
        }
    }
      
    /**
     * Creates new form createacc2
     */
      public createacc2() {
        initComponents();
       
         bg.setIcon(sql_connection.scaleimg(bg.getWidth(),bg.getHeight()));
        captcha();
        
    }
    public createacc2(String fn, String ln, String un, String pwd) {
        initComponents();
       
          bg.setIcon(sql_connection.scaleimg(bg.getWidth(),bg.getHeight()));
        captcha();
        username= un;
        firstname= fn;
        lastname= ln;
        pwd1=pwd;
        System.out.println(username+""+firstname+""+lastname+""+pwd1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logtext = new javax.swing.JLabel();
        mailtext = new javax.swing.JLabel();
        sign_in = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        createacc = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        mailtext4 = new javax.swing.JLabel();
        cap_ans = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        mailtext1 = new javax.swing.JLabel();
        captcha = new javax.swing.JLabel();
        phoneno = new javax.swing.JTextField();
        combobox = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logtext.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        logtext.setText("Create Account");
        jPanel2.add(logtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 310, 40));

        mailtext.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext.setText("Enter the characters as shown");
        jPanel2.add(mailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        sign_in.setBackground(new java.awt.Color(0, 163, 0));
        sign_in.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        sign_in.setForeground(new java.awt.Color(255, 255, 255));
        sign_in.setText("Sign In");
        sign_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_inMouseClicked(evt);
            }
        });
        sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_inActionPerformed(evt);
            }
        });
        jPanel2.add(sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 240, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setText("Already have an account?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        createacc.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        createacc.setText("Log In");
        createacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createaccMouseClicked(evt);
            }
        });
        jPanel2.add(createacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 80, -1));

        email.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 220, -1));

        mailtext4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext4.setText("Email Id");
        jPanel2.add(mailtext4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        cap_ans.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cap_ans.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cap_ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap_ansActionPerformed(evt);
            }
        });
        jPanel2.add(cap_ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 220, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 560, 10));

        mailtext1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext1.setText("Phone Number");
        jPanel2.add(mailtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        captcha.setBackground(new java.awt.Color(255, 255, 255));
        captcha.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        captcha.setText("captcha");
        jPanel2.add(captcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 120, 30));

        phoneno.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        phoneno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });
        jPanel2.add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 220, -1));

        combobox.setText("Customer");
        combobox.setBorder(javax.swing.BorderFactory.createTitledBorder("Account Type\n"));
        jPanel2.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 180, 60));

        jButton1.setText("Reset Captcha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 640, 450));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccMouseClicked
        // TODO add your handling code here:
        //Go back to login screen
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createaccMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void cap_ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cap_ansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cap_ansActionPerformed

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void sign_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_inMouseClicked
        // TODO add your handling code here:
        
        /*  try {
            
            ps=sql_connection.conneect_DB().prepareStatement("INSERT INTO `users`(`firstname`, `lastname`, `username`, `password`, `email`, `Phone_Number`, `Account_Type`) VALUES (?,?,?,?,?,?,?)");
            ps.setString(1, firstname);
            ps.setString(2,lastname );
            ps.setString(3, username);
            ps.setString(4, pwd1);
            ps.setString(5, email.getText());
            ps.setString(6, phoneno.getText());
            ps.setString(7, String.valueOf(acctype.getSelectedItem()));

            
            JOptionPane.showMessageDialog(null, "Data Base addition completed");

        } catch (SQLException ex) {
            // Logger.getLogger(Databaseaddi_Sqlite.class.getName()).log(Level.SEVERE, null, ex);
        }*/

    }//GEN-LAST:event_sign_inMouseClicked

    private void sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_inActionPerformed
        // TODO add your handling code here:
        //Checking validation for all fields
        if(phoneno.getText().equalsIgnoreCase("")||email.getText().equalsIgnoreCase("")
                ||cap_ans.getText().equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(this," Please Enter All Fields");        
        else if(phoneno.getText().length()!=10)//CHECKING IF PHONE NO. IS 10 DIGITS
            JOptionPane.showMessageDialog(this," Enter Valid Phone number");
       else{//CHECKING IF CAPTCHA ANSWERS MATCH
            if(cap_ans.getText().equals(captcha.getText())){
                try
               {   //INSERTING NEW RECORD
            ps=sql_connection.conneect_DB().prepareStatement("insert into users values(?,?,?,?,?,?,?)");
            ps.setString(1, firstname);
            ps.setString(2,lastname );
            ps.setString(3, username);
            ps.setString(4, pwd1);
            ps.setString(5, email.getText());
            ps.setString(6, phoneno.getText());
            ps.setString(7, combobox.getText());
            int i=ps.executeUpdate();
            if(i==1){
                JOptionPane.showMessageDialog(null,"Record added successfully");
            }
            login ln=new login();//OPENING LOGIN FORM
            ln.setVisible(true);
            this.dispose();
            }
        catch (SQLException ex) {}
            }
            else
                JOptionPane.showMessageDialog(null,"inccorect Captcha");
        }
    }//GEN-LAST:event_sign_inActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        captcha.setText("");
        sb.delete(0,6);
        captcha();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createacc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createacc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createacc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createacc2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new createacc2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JTextField cap_ans;
    private javax.swing.JLabel captcha;
    private javax.swing.JLabel combobox;
    private javax.swing.JLabel createacc;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logtext;
    private javax.swing.JLabel mailtext;
    private javax.swing.JLabel mailtext1;
    private javax.swing.JLabel mailtext4;
    private javax.swing.JTextField phoneno;
    private javax.swing.JButton sign_in;
    // End of variables declaration//GEN-END:variables
}
