/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ia;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */
public class forgot_pwd2 extends javax.swing.JFrame {
    PreparedStatement ps87;
    String un="";
 StringBuilder sb = new StringBuilder(6);
    /**
     * Creates new form forgot_pwd2
     */
    public void captcha(){ //Autogenerating captacha code 
    String AlphaNumericString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                 + "0123456789"
                                 + "abcdefghijklmnopqrstuvxyz";
        // create StringBuffer size of AlphaNumericString
        for (int i = 0; i < 6; i++) {
            // generate a random number between
            // 0 to AlphaNumericString variable length
            int index = (int)(AlphaNumericString.length()
                        * Math.random());
              // add Character one by one in end of sb
            sb.append(AlphaNumericString.charAt(index));
            captcha.setText(sb.toString());
        }
    }
    public forgot_pwd2() {
        initComponents();
          bg.setIcon(sql_connection.scaleimg(bg.getWidth(),bg.getHeight()));
          captcha();
          un="";
    }
     public forgot_pwd2(String user) {
        initComponents();
        un=user;
        captcha();
        bg.setIcon(sql_connection.scaleimg(bg.getWidth(),bg.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logtext = new javax.swing.JLabel();
        mailtext = new javax.swing.JLabel();
        reset_pwd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        createacc = new javax.swing.JLabel();
        mailtext4 = new javax.swing.JLabel();
        cap_ans = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        mailtext1 = new javax.swing.JLabel();
        captcha = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        crtpwd = new javax.swing.JPasswordField();
        showpwd = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logtext.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        logtext.setText("Forgot Password");
        jPanel2.add(logtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 310, 40));

        mailtext.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext.setText("Enter the characters as shown");
        jPanel2.add(mailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        reset_pwd.setBackground(new java.awt.Color(0, 163, 0));
        reset_pwd.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        reset_pwd.setForeground(new java.awt.Color(255, 255, 255));
        reset_pwd.setText("Reset Password");
        reset_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_pwdActionPerformed(evt);
            }
        });
        jPanel2.add(reset_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 240, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setText("Already have an account?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        createacc.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        createacc.setText("Log In");
        createacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createaccMouseClicked(evt);
            }
        });
        jPanel2.add(createacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 80, -1));

        mailtext4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext4.setText("New Password");
        jPanel2.add(mailtext4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        cap_ans.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cap_ans.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cap_ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap_ansActionPerformed(evt);
            }
        });
        jPanel2.add(cap_ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 220, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 560, 10));

        mailtext1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext1.setText("Confirm Password");
        jPanel2.add(mailtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        captcha.setBackground(new java.awt.Color(255, 255, 255));
        captcha.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        captcha.setText("captcha");
        jPanel2.add(captcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 120, 30));

        pwd.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        pwd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 220, 30));

        crtpwd.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        crtpwd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(crtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 220, 30));

        showpwd.setBackground(new java.awt.Color(255, 255, 255));
        showpwd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        showpwd.setText("Show Password");
        showpwd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showpwdItemStateChanged(evt);
            }
        });
        jPanel2.add(showpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jButton1.setText("Reset Captcha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 640, 450));
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccMouseClicked
        // TODO add your handling code here:
        //go back to login screen
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createaccMouseClicked

    private void cap_ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cap_ansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cap_ansActionPerformed

    private void showpwdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showpwdItemStateChanged
        // TODO add your handling code here:
        //show password
        if(showpwd.isSelected()==true)
        {
            crtpwd.setEchoChar((char) 0);
            pwd.setEchoChar((char) 0);
        }
        else
        {
            crtpwd.setEchoChar('*');
            pwd.setEchoChar('*');
        }
    }//GEN-LAST:event_showpwdItemStateChanged

    private void reset_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_pwdActionPerformed
        //Checking whether all fields are filled        
        if(crtpwd.getText().equalsIgnoreCase("")||pwd.getText().equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(null,"Enter Password");
        else if(cap_ans.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Enter Captcha");
        else{
        try{
            if(crtpwd.getText().equals(pwd.getText()))//Checki(crtpwd.getText().equals(pwd.getText()))/ng if passwords match 
            {    //checking if captcha answer is correct
                if(captcha.getText().equals(cap_ans.getText())){
                    //Updating password
                    System.out.println("try");
             String sql = "UPDATE users SET password= ? where username= ?";
             ps87 = sql_connection.conneect_DB1().prepareStatement(sql);
             ps87.setString(1, pwd.getText());
             ps87.setString(2, un);
              System.out.println(ps87);
             int i=ps87.executeUpdate();
              
             
             System.out.println("i="+i);
                if(i==1){
                    JOptionPane.showMessageDialog(null, "Password has been changed!");
                    login ln=new login();
                    ln.setVisible(true);
                    this.dispose();}}
                else
                    JOptionPane.showMessageDialog(null,"Incorrect Captcha");
            }
            else{
            JOptionPane.showMessageDialog(null, "Password entered do not match!");
            }
        } catch (SQLException ex) {}}
    }//GEN-LAST:event_reset_pwdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        captcha.setText("");
        sb.delete(0,6);
        captcha();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_pwd2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_pwd2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_pwd2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_pwd2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_pwd2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JTextField cap_ans;
    private javax.swing.JLabel captcha;
    private javax.swing.JLabel createacc;
    private javax.swing.JPasswordField crtpwd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logtext;
    private javax.swing.JLabel mailtext;
    private javax.swing.JLabel mailtext1;
    private javax.swing.JLabel mailtext4;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton reset_pwd;
    private javax.swing.JCheckBox showpwd;
    // End of variables declaration//GEN-END:variables
}
