/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ia;

import java.awt.Image;
import javax.mail.internet.InternetAddress;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.mail.Session;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.mail.Authenticator;
import javax.mail.internet.MimeMessage;


/**
 *
 * @author Yash
 */
public class forgot_pwd extends javax.swing.JFrame {
    String un="",otp="",codeans="";
    PreparedStatement ps;
    ResultSet rs;
    StringBuilder sb = new StringBuilder(4);
    
    //autogenerating code to send via email
    public void captcha(){
    String AlphaNumericString = "0123456789";
                                   
  
        // create StringBuffer size of AlphaNumericString
       
  
        for (int i = 0; i < 4; i++) {
  
            // generate a random number between
            // 0 to AlphaNumericString variable length
            int index
                = (int)(AlphaNumericString.length()
                        * Math.random());
  
            // add Character one by one in end of sb
            sb.append(AlphaNumericString.charAt(index));
            otp=sb.toString();
        }
    }
 
    /**
     * Creates new form forgot_pwd
     */
  public forgot_pwd() {
        initComponents();
        
    }
    public forgot_pwd(String username) {
        initComponents();
          bg.setIcon(sql_connection.scaleimg(bg.getWidth(),bg.getHeight()));
                un=username;
                uname.setText(un);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logtext = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        createacc = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        createacc1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        showpwd = new javax.swing.JCheckBox();
        uname = new javax.swing.JTextField();
        send_otp = new javax.swing.JButton();
        otpans = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logtext.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        logtext.setText("Forgot Password");
        jPanel2.add(logtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 310, 40));

        next.setBackground(new java.awt.Color(0, 163, 0));
        next.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 240, 30));

        createacc.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        createacc.setText("Sign In Instead");
        createacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createaccMouseClicked(evt);
            }
        });
        jPanel2.add(createacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 560, 10));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("If you have forgotten your password, simply enter your \nusername and click on the send code button.\nThen enter the code sent on you registered e-mail address\ninto the field\n");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 550, -1));

        createacc1.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        createacc1.setText("Log In Instead");
        createacc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createacc1MouseClicked(evt);
            }
        });
        jPanel2.add(createacc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 150, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Enter OTP:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        showpwd.setBackground(new java.awt.Color(255, 255, 255));
        showpwd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        showpwd.setText("Show Password");
        showpwd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showpwdItemStateChanged(evt);
            }
        });
        jPanel2.add(showpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        uname.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        uname.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Enter Username\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 16))); // NOI18N
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 250, -1));

        send_otp.setText("Send OTP");
        send_otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_otpActionPerformed(evt);
            }
        });
        jPanel2.add(send_otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        otpans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otpansMouseClicked(evt);
            }
        });
        jPanel2.add(otpans, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 640, 450));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        //Going to next forgot password form
        //checking if input otp=sent otp
        if(codeans.equals(""))
        {
        JOptionPane.showMessageDialog(this,"enter code");
        }
        else{
        if(codeans.equals(otpans.getText())){
            forgot_pwd2 fp=new forgot_pwd2(uname.getText());
            fp.setVisible(true);
            this.dispose();}
        else
            JOptionPane.showMessageDialog(this, "Incorrect OTP");}
    }//GEN-LAST:event_nextActionPerformed

    private void createaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccMouseClicked
        // TODO add your handling code here:
        //Going to creataccount form
        new createacc().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createaccMouseClicked

    private void createacc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createacc1MouseClicked
        // TODO add your handling code here:
        //Going back to login form
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createacc1MouseClicked

    private void showpwdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showpwdItemStateChanged
        // TODO add your handling code here:
        if(showpwd.isSelected()==true)
        {
            otpans.setEchoChar((char) 0);
        }
        else
        {
            otpans.setEchoChar('*');
        }
    }//GEN-LAST:event_showpwdItemStateChanged

    private void send_otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_otpActionPerformed
        // TODO add your handling code here:
        //Sending otp
        try{   
            ps=sql_connection.conneect_DB().prepareStatement("SELECT * FROM users WHERE Username=?");
            ps.setString(1, uname.getText());
            rs=ps.executeQuery();
            if(rs.next()==false){
                JOptionPane.showMessageDialog(this,"username not found");
            }
            else{
              captcha();
             // code to send email
              String to = rs.getString("email");
              String subject = "Reset Code";
              codeans=String.valueOf(otp);//otp is obtained from captcha()
              String Content = "Your reset code is "+codeans;
              System.out.print(Content); 
              Properties properties = new Properties();
              properties.put("mail.smtp.auth","true");
              properties.put("mail.smtp.starttls.enable","true");
              properties.put("mail.smtp.host","smtp.gmail.com");
              properties.put("mail.smtp.port","587");
              String sendAccount = "theashcafe@gmail.com";
              String password = "ashcafe123$";
              Session session;
              session = Session.getInstance(properties, new Authenticator(){
              @Override
              protected javax.mail.PasswordAuthentication getPasswordAuthentication(){
              return new javax.mail.PasswordAuthentication(sendAccount,password);
              }
              });
            try {
            MimeMessage message =  new MimeMessage(session);
            message.setFrom(new InternetAddress(sendAccount));
            message.setRecipient(javax.mail.Message.RecipientType.TO, new InternetAddress(to));
            message.setSubject(subject);
            message.setText(Content);
            javax.mail.Transport.send(message);
            JOptionPane.showMessageDialog(null, "Code has been sent to your email");
            } catch (Exception ex) {
            System.out.println(ex);        
                }}}       
            catch(SQLException ex){}
         
         
    }//GEN-LAST:event_send_otpActionPerformed

    private void otpansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otpansMouseClicked
        // TODO add your handling code here:
        next.enable(true);
    }//GEN-LAST:event_otpansMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_pwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_pwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_pwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_pwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_pwd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel createacc;
    private javax.swing.JLabel createacc1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logtext;
    private javax.swing.JButton next;
    private javax.swing.JPasswordField otpans;
    private javax.swing.JButton send_otp;
    private javax.swing.JCheckBox showpwd;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
