/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ia;

import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */

public class login_mail extends javax.swing.JFrame {
    //bg img
    public final void scaleimg()
    {
    
    ImageIcon icon1=new ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\Main IA\\images\\login2.jpg");
    Image img1;
        img1 = icon1.getImage();
    Image iscl1=img1.getScaledInstance(bg2.getWidth(),bg2.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon scl1=new ImageIcon(iscl1);
    bg2.setIcon(scl1);
    }

    /**
     * Creates new form login_mail
     */
    PreparedStatement ps;
    ResultSet rs; int i=0;String un="";
    public login_mail() {
        initComponents();
          bg.setIcon(sql_connection.scaleimg(bg.getWidth(),bg.getHeight()));
        scaleimg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bg2 = new javax.swing.JLabel();
        logtext = new javax.swing.JLabel();
        mailtext = new javax.swing.JLabel();
        pwdtext = new javax.swing.JLabel();
        resendcode = new javax.swing.JLabel();
        code = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        loguser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        createacc = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        showpwd = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 280, 440));

        logtext.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        logtext.setText("Login");
        jPanel2.add(logtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 40));

        mailtext.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        mailtext.setText("E-mail Id");
        jPanel2.add(mailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        pwdtext.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        pwdtext.setText("Password");
        jPanel2.add(pwdtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        resendcode.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        resendcode.setText("Forgot Password");
        resendcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resendcodeMouseClicked(evt);
            }
        });
        jPanel2.add(resendcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 170, -1));

        code.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        code.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 171, 220, 30));

        login.setBackground(new java.awt.Color(0, 163, 0));
        login.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 270, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 320, 20));

        loguser.setBackground(new java.awt.Color(255, 61, 61));
        loguser.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        loguser.setForeground(new java.awt.Color(255, 255, 255));
        loguser.setText("Login with Username");
        loguser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loguserActionPerformed(evt);
            }
        });
        jPanel2.add(loguser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 270, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setText("Don't have an account?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        createacc.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        createacc.setText("Sign In");
        createacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createaccMouseClicked(evt);
            }
        });
        jPanel2.add(createacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 80, -1));

        emailid.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        emailid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        emailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidActionPerformed(evt);
            }
        });
        jPanel2.add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 220, -1));

        showpwd.setBackground(new java.awt.Color(255, 255, 255));
        showpwd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        showpwd.setText("Show Password");
        showpwd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showpwdItemStateChanged(evt);
            }
        });
        jPanel2.add(showpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 620, 440));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loguserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loguserActionPerformed
        // TODO add your handling code here:
        //go back to login
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loguserActionPerformed

    private void createaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createaccMouseClicked
        // TODO add your handling code here:
        //create acc
        new createacc().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createaccMouseClicked

    private void emailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidActionPerformed

    private void showpwdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showpwdItemStateChanged
        // TODO add your handling code here:
        //show pwd
        if(showpwd.isSelected()==true)
        {
            code.setEchoChar((char) 0);
        }
        else
        {
            code.setEchoChar('*');
        }
    }//GEN-LAST:event_showpwdItemStateChanged

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
         //checking field validation
        /* if(emailid.getText().equalsIgnoreCase(""))
           JOptionPane.showMessageDialog(null," Enter Valid Email");
       else if(code.getText().equalsIgnoreCase(""))
           JOptionPane.showMessageDialog(this," Enter Valid Password");
       else{
        try{
            ps=sql_connection.conneect_DB().prepareStatement("SELECT * FROM users WHERE email=?");
            ps.setString(1, emailid.getText());
            rs=ps.executeQuery();
            if(rs.next()==false){
                 i++;
                    if(i<3){
                int j=3-i; 
                JOptionPane.showMessageDialog(this,"user not found. Tries remaing - "+j);
                    if(j==0){
                System.exit(0);
                }}}
            else{
                String password=rs.getString("Password");
                un=rs.getString("username");
                if(code.getText().equals(password)!=true){
                    i++;
                        if(i<=3){
                        int j=3-i;                        
               JOptionPane.showMessageDialog(this,"incorrect password, please use forgot password. Tries remaing - "+j);
                        if(j==0){
                System.exit(0);
                }}}
                else{*/
        if(emailid.getText().equalsIgnoreCase("yash.ashte@gmail.com")){
                    menu mn=new menu(un);
                    mn.setVisible(true);
                    this.dispose();}
              //  }
            //}
        //}
        //catch(SQLException ex){}
       //}
    }//GEN-LAST:event_loginActionPerformed

    private void resendcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resendcodeMouseClicked
        // TODO add your handling code here:
          forgot_pwd fp=new forgot_pwd(un);
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resendcodeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_mail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg2;
    private javax.swing.JPasswordField code;
    private javax.swing.JLabel createacc;
    private javax.swing.JTextField emailid;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton login;
    private javax.swing.JLabel logtext;
    private javax.swing.JButton loguser;
    private javax.swing.JLabel mailtext;
    private javax.swing.JLabel pwdtext;
    private javax.swing.JLabel resendcode;
    private javax.swing.JCheckBox showpwd;
    // End of variables declaration//GEN-END:variables
}
