/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ia;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash
 */
public class login extends javax.swing.JFrame {
     Connection cin;
    ResultSet rs;
    PreparedStatement ps;
    int i=0;
     /**
     * Creates new form login
     */
    public login() {
       
        initComponents();
        //setting background images
        bg.setIcon(sql_connection.scaleimg(bg.getWidth(),bg.getHeight()));
        ImageIcon icon1=new ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\Main IA\\images\\login2.jpg");
        Image img1;
        img1 = icon1.getImage();
        Image iscl1=img1.getScaledInstance(bg2.getWidth(),bg2.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scl1=new ImageIcon(iscl1);
        bg2.setIcon(scl1);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bg2 = new javax.swing.JLabel();
        logtext = new javax.swing.JLabel();
        forpwd = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        loginwmail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        showpwd = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel2.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 270, 440));

        logtext.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        logtext.setText("Login");
        jPanel2.add(logtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 40));

        forpwd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        forpwd.setText("Forgot Password");
        forpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forpwdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forpwdMouseEntered(evt);
            }
        });
        jPanel2.add(forpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 140, 20));

        pwd.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        pwd.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Password\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 16))); // NOI18N
        jPanel2.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, 60));

        login.setBackground(new java.awt.Color(0, 163, 0));
        login.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 270, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 320, 20));

        loginwmail.setBackground(new java.awt.Color(255, 61, 61));
        loginwmail.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        loginwmail.setForeground(new java.awt.Color(255, 255, 255));
        loginwmail.setText("Login with E-mail");
        loginwmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginwmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginwmailActionPerformed(evt);
            }
        });
        jPanel2.add(loginwmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 270, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setText("Don't have an account?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel3.setText("Sign In");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 80, -1));

        username.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Username\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 16))); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, -1));

        showpwd.setBackground(new java.awt.Color(255, 255, 255));
        showpwd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        showpwd.setText("Show Password");
        showpwd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showpwdItemStateChanged(evt);
            }
        });
        jPanel2.add(showpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 620, 440));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forpwdMouseClicked
        // TODO add your handling code here:
// go to forgot pwd form
        forgot_pwd fp=new forgot_pwd(username.getText());
        fp.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_forpwdMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        //Check username and pawword
       if(username.getText().equalsIgnoreCase(""))
           JOptionPane.showMessageDialog(this," Enter Valid Username");//validating whether field is filled
       else if(pwd.getText().equalsIgnoreCase(""))
           JOptionPane.showMessageDialog(this," Enter Valid Password");//validating whether field is filled
       else{
            try{
                   ps=sql_connection.conneect_DB().prepareStatement("SELECT * FROM users WHERE username=?");
                   ps.setString(1, username.getText());
                   rs=ps.executeQuery();
                   if(rs.next()==false){              
                        i++;
                        if(i<=3) {
                        int j=3-i; 
                        System.out.println(i+""+j);
                        JOptionPane.showMessageDialog(this,"username not found. Tries remaing - "+j);
                        if(j==0){
                            System.exit(0);             
                                }}}
                        else{
                         String password=rs.getString("Password");
                         if(pwd.getText().equals(password)!=true){
                             i++;
                            if(i<=3){
                                int j=3-i;                
                                
            JOptionPane.showMessageDialog(this,"incorrect password, please use forgot password. Tries remaing - "+j);
                                if(j==0){
                                    System.exit(0);
                                              }}}            
                 //CHeck acc type
                    else{
                        String acc=rs.getString("account_type");
                        if(acc.equalsIgnoreCase("Customer")){
                            System.out.println("work");
                            menu mn=new menu(username.getText());
                            mn.setVisible(true);
                            mn.tab_number();
                            this.dispose();
                            }
                        else{
                            man_home mh=new man_home();
                            mh.setVisible(true);
                            this.dispose();
                            }
                        }     
                    }
                 }
        catch(SQLException ex){ }
            }
    }//GEN-LAST:event_loginActionPerformed

    private void loginwmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginwmailActionPerformed
        // TODO add your handling code here:\
        new login_mail().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_loginwmailActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new createacc().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void showpwdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showpwdItemStateChanged
        // TODO add your handling code here:
        if(showpwd.isSelected()==true)
        {
            pwd.setEchoChar((char) 0);//pwd is shown using alphanumeric characters
        }
        else
        {
            pwd.setEchoChar('*');//pwd is shown using *
        }
    }//GEN-LAST:event_showpwdItemStateChanged

    private void forpwdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forpwdMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_forpwdMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel forpwd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton login;
    private javax.swing.JButton loginwmail;
    private javax.swing.JLabel logtext;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JCheckBox showpwd;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
