/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.ia;

import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */
public class man_orders extends javax.swing.JFrame {

    /**
     * Creates new form man_orders
     */
    DefaultTableModel dtm = new DefaultTableModel();
     Statement smt;
    PreparedStatement pst;
    ResultSet rs1,rs7;
    String on="";
    
    //Database to table
    public void retrieve(){
try
    {
            
        
       smt=( sql_connection.conneect_DB().createStatement());
            menuTable.setModel(dtm);
            menuTable.setAutoscrolls(true);
            dtm.addColumn("Order Number");
            dtm.addColumn("Username");
            dtm.addColumn("Dish Name");
              dtm.addColumn("Quantity");
            dtm.addColumn("Cost");           
            dtm.addColumn("Veg/Non-Veg");
            dtm.addColumn("Type");
            dtm.addColumn("Status");
           
          
            String sql = "select * from orders";
           
            pst =  sql_connection.conneect_DB().prepareStatement(sql);
            rs1 = pst.executeQuery();
            
            menuTable.setDefaultEditor(Object.class, null);
            while (rs1.next())
            {
                         
                dtm.addRow(new Object[] { rs1.getString("ordernum"),rs1.getString("username"),rs1.getString("dishname"), rs1.getString("quantity"), rs1.getString("cost"),rs1.getString("veg_nonveg"),rs1.getString("dish_type"),rs1.getString("status")});
            }
        
    }
    catch (SQLException ex)
    {
        System.out.println(ex);
    }
    }
    
    //bg img
    public final void scaleimg()
    {
    
    ImageIcon icon1=new ImageIcon("C:\\Users\\Yash\\Documents\\NetBeansProjects\\Main IA\\src\\main\\ia\\search icon.png");
   
      Image  img1 = icon1.getImage();
    Image iscl1=img1.getScaledInstance(search_icon.getWidth(),search_icon.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon scl1=new ImageIcon(iscl1);
    search_icon.setIcon(scl1);
    }

    public man_orders() {
        initComponents();
        retrieve();
        scaleimg();
        jLabel7.setText(String.valueOf(menuTable.getRowCount()));
         bg.setIcon(sql_connection.scaleimg(bg.getWidth(),bg.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        search_box = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        search_icon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Recent Orders");
        jLabel1.setOpaque(true);

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        menuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menuTable);

        jLabel2.setText("Order Number -");

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel5.setText("Search");

        search_box.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        search_box.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Number of Orders today -");

        search_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_iconMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel8.setText("Back to Home");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(111, 111, 111))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(search_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(search_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 810, 490));
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTableMouseClicked
        // TODO add your handling code here
       //table to text field
        try{
            menuTable.setModel(dtm);
            int selcrow = menuTable.getSelectedRow();
            menuTable.setEnabled(true);

            jLabel3.setText(dtm.getValueAt(selcrow,0).toString());
            
        }
         catch(Exception ex)
        {

        }
    }//GEN-LAST:event_menuTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //accept  order
        try{            
            String stat="Accepted";//creating the status
            on=jLabel3.getText();//getting order number
            //Updating a record using order number as criteria
            String sql = "UPDATE orders SET status='"+stat+"' Where ordernum='"+on+"'";
            pst = sql_connection.conneect_DB().prepareStatement(sql);
            pst.executeUpdate();//executing 
            JOptionPane.showMessageDialog(null, "Order Accepted!");
            int i=0;
            while(i<dtm.getRowCount()){
                dtm.removeRow(i);//removing all rows           
            }
             sql = "select * from orders";
           
            pst =  sql_connection.conneect_DB().prepareStatement(sql);
            rs1 = pst.executeQuery();
            
            menuTable.setDefaultEditor(Object.class, null);
            while (rs1.next())
            {
                  
                dtm.addRow(new Object[] { rs1.getString("ordernum"),rs1.getString("username"),rs1.getString("dishname"), rs1.getString("quantity"), rs1.getString("cost"),rs1.getString("veg_nonveg"),rs1.getString("dish_type"),rs1.getString("status")});
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(man_orders.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //reject order
         try{
            on=jLabel3.getText();//getting order number
            //deleting using ordernumber as criteria
            String sql = "Delete From orders Where ordernum='"+on+"'";
            pst = sql_connection.conneect_DB1().prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record has been Deleted!");
            int i=0;
            while(i<dtm.getRowCount()){
                dtm.removeRow(i);}//removing all rows
            //creating table again to include updates
         String sql69 = "select * from orders";
           
            pst =  sql_connection.conneect_DB().prepareStatement(sql69);
            rs1 = pst.executeQuery();
            
            menuTable.setDefaultEditor(Object.class, null);
            while (rs1.next())
            {
                         
                dtm.addRow(new Object[] { rs1.getString("ordernum"),rs1.getString("username"),rs1.getString("dishname"), rs1.getString("quantity"), rs1.getString("cost"),rs1.getString("veg_nonveg"),rs1.getString("dish_type"),rs1.getString("status")});
            }   
        }
         
        catch (SQLException ex)
        {
            Logger.getLogger(man_orders.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void search_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_iconMouseClicked
        // TODO add your handling code here:
        //search orders
          try {
            
            String xp2 = search_box.getText();
            String sql1 ="SELECT * FROM `orders` WHERE `dishname` = '"+xp2+"'";
            PreparedStatement ps1 = sql_connection.conneect_DB().prepareStatement(sql1);
            rs7 = ps1.executeQuery();
            
             menuTable.setModel(dtm);
            menuTable.setAutoscrolls(true);
           
           
           
           
                     
            menuTable.setDefaultEditor(Object.class, null);
            int trow=dtm.getRowCount();

            for(int i=trow-1;i>=0;i--){
                dtm.removeRow(i);
            }
            while (rs7.next())
            {
                dtm.addRow(new Object[] { rs7.getString("ordernum"),rs7.getString("username"),rs7.getString("dishname"), rs7.getString("quantity"), rs7.getString("cost"),rs7.getString("veg_nonveg"),rs7.getString("dish_type"),rs7.getString("status")});          
                
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search_iconMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         man_home mh=new man_home();
        mh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(man_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(man_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(man_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(man_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new man_orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable menuTable;
    private javax.swing.JTextField search_box;
    private javax.swing.JLabel search_icon;
    // End of variables declaration//GEN-END:variables
}
